# Generated by Django 4.2.8 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhiVanChuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenKhuVuc', models.CharField(max_length=100, unique=True, verbose_name='Khu vực')),
                ('phiShip', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Phí vận chuyển (đ)')),
                ('thoiGianGiao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thời gian giao dự kiến')),
            ],
            options={
                'verbose_name': 'Phí vận chuyển',
                'verbose_name_plural': 'Phí vận chuyển',
            },
        ),
    ]
