# Generated by Django 6.0.1 on 2026-04-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_phivanchuyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tên chủ tài khoản'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số tài khoản'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên ngân hàng'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('picking', 'Chờ lấy hàng'), ('returning_to_warehouse', 'Đang chuyển về kho'), ('received', 'Đã nhận hàng'), ('processing', 'Đang xử lý'), ('completed', 'Đã hoàn tiền'), ('rejected', 'Từ chối')], default='pending', max_length=22, verbose_name='Trạng thái'),
        ),
    ]
