# Generated by Django 6.0.1 on 2026-04-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_returnrequest_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='refund_proof',
            field=models.ImageField(blank=True, null=True, upload_to='refund_proofs/', verbose_name='Biên lai hoàn tiền'),
        ),
    ]
