# Generated by Django 5.2.13 on 2026-05-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_returnrequest_refund_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú của Admin (Lý do từ chối)'),
        ),
    ]
