# Generated by Django 5.2.13 on 2026-05-01 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_returnrequest_admin_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
