# Generated by Django 6.0.1 on 2026-05-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_seed_categories_and_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='customer_return_proof',
            field=models.FileField(blank=True, null=True, upload_to='customer_return_proofs/', verbose_name='Ảnh/Video sản phẩm trả'),
        ),
    ]
